services:
  server:
    image: eeephemera/zvk-requests-server:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zvk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zvk-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      server:
        condition: service_healthy
    networks:
      - zvk-network

networks:
  zvk-network:
    driver: bridge

volumes:
  postgres_data: