services:
  # Клиентская часть (Next.js)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: zvk_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8081/api
    depends_on:
      - server

  # Серверная часть (Go)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zvk_server
    restart: always
    env_file:
      - server/.env
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: zvk_postgres
    restart: always
    env_file:
      - server/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
