name: gosec

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache-dependency-path: server/go.sum
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        working-directory: server
        run: $(go env GOPATH)/bin/gosec ./...

